DATABASE_URL: "postgres://postgres:password@localhost:5432/postsdb?sslmode=disable"
PORT: "8080"
JWT_SECRET: "my_secret_token"
ACCESS_KEY: "M8Kjf3vpymphKULcLzJn"
SECRET_KEY: "Un1Xkp29Sq8TOYZixlurgBpUwyqhUGlLtAadpkqG"
MINIO_BUCKET: "crudexample"